config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  root 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create]
  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      post 'delivered'
      post 'canceled'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier, required: true
  has_many :order_items
  has_many :orders, through: :order_items

  validates :name, :sku, :weight, :width, :height, :depth, presence: true
  validates :sku, length: { is: 20 }
  validates :sku, uniqueness: true
  validates :weight, :width, :height, :depth, numericality: { only_integer: true, greater_than: 0 }

  def description
    "#{self.name} (#{self.sku})"
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :create]
  before_action :set_product_model, only: [:show, :edit, :update]

  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.order(:brand_name)
  end

  def create
    @product_model = ProductModel.new(product_model_params)

    if @product_model.save
      redirect_to @product_model, notice: 'Modelo de produto cadastrado com sucesso.'
    else
      @suppliers = Supplier.order(:brand_name)
      flash.now[:notice] = 'Falha ao cadastrar o modelo de produto.'
      render :new
    end
  end

  private

  def set_product_model
    @product_model = ProductModel.find(params[:id])
  end

  def product_model_params
    params.require(:product_model).permit(:name, :sku, :weight, :width, :height, :depth, :supplier_id)
  end
end

app/views/product_models/_form.html.erb
<%= form_with model: @product_model do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :sku %>
    <%= f.text_field :sku %>
  </div>
  <div>
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>
  <div>
    <%= f.label :width %>
    <%= f.number_field :width %>
  </div>
  <div>
    <%= f.label :height %>
    <%= f.number_field :height %>
  </div>
  <div>
    <%= f.label :depth %>
    <%= f.number_field :depth %>
  </div>
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name, prompt: true %>
  </div>
  
  <%= f.submit 'Enviar' %>
<% end %>

app/views/product_models/index.html.erb
<h2><%= I18n.t 'activerecord.models.product_model.other' %></h2>

<%= link_to 'Cadastrar Modelo de Produto', new_product_model_path %>
<%= link_to 'Voltar', root_path %>

<% if @product_models.any? %>
  <% @product_models.each do |product_model| %>
    <div>
      <h3><%= link_to product_model.name, product_model %></h3>

      <dl>
        <dt><%= I18n.t 'activerecord.attributes.product_model.sku' %>:</dt>
        <dd><%= product_model.sku %></dd>

        <dt><%= I18n.t 'activerecord.attributes.product_model.name' %>:</dt>
        <dd><%= product_model.supplier.brand_name %></dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <p>Não existem modelos de produtos cadastrados.</p>
<% end %>

app/views/product_models/new.html.erb
<h3><%= I18n.t 'views.product_models.new_product_model' %></h3>

<% if @product_model.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  
  <% @product_model.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/product_models/show.html.erb
<h2><%= @product_model.name %></h2>

<div>
  <dl>
    <dt><strong><%= I18n.t 'activerecord.attributes.product_model.sku' %>:</strong></dt>
    <dd><%= @product_model.sku %></dd>

    <dt><strong><%= I18n.t 'activerecord.attributes.product_model.weight' %>:</strong></dt>
    <dd><%= number_with_delimiter(@product_model.weight, delimiter: '.') %>g</dd>

    <dt><strong><%= I18n.t 'activerecord.attributes.product_model.width' %>:</strong></dt>
    <dd><%= number_with_delimiter(@product_model.width, delimiter: '.') %>cm</dd>

    <dt><strong><%= I18n.t 'activerecord.attributes.product_model.height' %>:</strong></dt>
    <dd><%= number_with_delimiter(@product_model.height, delimiter: '.') %>cm</dd>

    <dt><strong><%= I18n.t 'activerecord.attributes.product_model.depth' %>:</strong></dt>
    <dd><%= number_with_delimiter(@product_model.depth, delimiter: '.') %>cm</dd>

    <dt><strong><%= I18n.t 'activerecord.attributes.product_model.supplier' %>:</strong></dt>
    <dd><%= @product_model.supplier.brand_name %></dd>
  </dl>
</div>