config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  root 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create]
  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      post 'delivered'
      post 'canceled'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  has_many :order_items
  has_many :product_models, through: :order_items

  enum status: { pending: 0, delivered: 5, canceled: 9 }

  before_validation :set_code, on: :create

  validates :code, :estimated_delivery_date, presence: true
  validates :estimated_delivery_date, comparison: { greater_than: Date.today, message: 'precisa ser futura' }

  private

  def set_code
    self.code = SecureRandom.alphanumeric(10).upcase if self.code.nil?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order_check_user, only: [:show, :edit, :update, :delivered, :canceled]

  def index
    @orders = current_user.orders
  end

  def show
  end

  def new
    @order = Order.new
    @warehouses = Warehouse.order(:name)
    @suppliers = Supplier.order(:corporate_name)
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    
    if @order.save
      redirect_to @order, notice: 'Pedido registrado com sucesso.'
    else
      @warehouses = Warehouse.order(:name)
      @suppliers = Supplier.order(:corporate_name)
      flash.now[:notice] = 'Falha ao registrar o pedido.'
      render :new
    end
  end

  def edit
    @warehouses = Warehouse.order(:name)
    @suppliers = Supplier.order(:corporate_name)
  end

  def update
    if @order.update(order_params)
      redirect_to @order
    else
      @warehouses = Warehouse.order(:name)
      @suppliers = Supplier.order(:corporate_name)
      flash.now[:notice] = 'Falha ao atualizar o pedido.'
      render :new
    end
  end

  def search
    @code = params[:query]
    @orders = Order.where('code LIKE ?', "%#{@code}%")
  end

  def delivered
    if @order.delivered!
      @order.order_items.each do |item|
        item.quantity.times do
          StockProduct.create!(order: @order, product_model: item.product_model, warehouse: @order.warehouse)
        end
      end
      redirect_to @order, notice: 'Pedido marcado como entregue.'
    else
      flash.now[:notice] = 'Falha ao marcar o pedido como entregue.'
      render :show
    end
  end

  def canceled
    if @order.canceled!
      redirect_to @order, notice: 'Pedido cancelado com sucesso.'
    else
      flash.now[:notice] = 'Falha ao cancelar o pedido.'
      render :show
    end
  end

  private

  def order_params
    params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
  end

  def set_order_check_user
    @order = Order.find(params[:id])
    redirect_to root_path if @order.user != current_user
  end
end

app/views/orders/_form.html.erb
<%= form_with model: @order do |f| %>
  <div>
    <%= f.label :warehouse_id %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description, prompt: true %>
  </div>
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :description, prompt: true %>
  </div>
  <div>
    <%= f.label :estimated_delivery_date %>
    <%= f.date_field :estimated_delivery_date %>
  </div>

  <%= f.submit 'Enviar' %>
<% end %>

app/views/orders/_order.html.erb
<dl>
  <dt><strong><%= t 'activerecord.attributes.order.user' %>:</strong></dt>
  <dd><%= order.user.description %></dd>

  <dt><strong><%= t 'activerecord.attributes.order.warehouse' %>:</strong></dt>
  <dd><%= order.warehouse.full_description %></dd>

  <dt><strong><%= t 'activerecord.attributes.order.supplier' %>:</strong></dt>
  <dd><%= order.supplier.corporate_name %></dd>

  <dt><strong><%= t 'activerecord.attributes.order.estimated_delivery_date' %>:</strong></dt>
  <dd><%= l(order.estimated_delivery_date) %></dd>

  <dt><strong><%= t 'activerecord.attributes.order.status' %>:</strong></dt>
  <dd><%= t(order.status) %></dd>
</dl>

app/views/orders/edit.html.erb
<h2><%= t '.edit_order' %> <%= @order.code %></h2>

<% if @order.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  
  <% @order.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/orders/index.html.erb
<h2><%= I18n.t 'activerecord.models.order.other' %></h2>

<%= link_to 'Cadastrar Pedido', new_order_path %>
<%= link_to 'Voltar', root_path %>

<% if @orders.any? %>
  <% @orders.each do |order| %>
    <div>
      <%= link_to order do %>
        <h3><%= t('activerecord.models.order.one') %> <%= order.code %></h3>
      <% end %>
      
      <%= render order %>
    </div>
  <% end %>
<% else %>
  <p>Você não realizou nenhum pedido.</p>
<% end %>

app/views/orders/new.html.erb
<h2><%= t '.new_order' %></h2>

<% if @order.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  
  <% @order.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<%= form_with model: @order do |f| %>
  <div>
    <%= f.label :warehouse_id %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description, prompt: true %>
  </div>
  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :description, prompt: true %>
  </div>
  <div>
    <%= f.label :estimated_delivery_date %>
    <%= f.date_field :estimated_delivery_date %>
  </div>

  <%= f.submit 'Registrar' %>
<% end %>

app/views/orders/search.html.erb
<h2><%= t '.title' %>: <%= @code %></h2>

<%= link_to 'Voltar', root_path %>

<% if @orders.any? %>
  <span><%= @orders.size %> <%= t('.count_message', count: @orders.size) %></span>

  <% @orders.each do |o| %>
    <div>
      <%= link_to o do %>
        <h3>Pedido <%= o.code %></h3>
      <% end %>

      <dl>
        <dt><%= t 'activerecord.attributes.order.warehouse' %>:</dt>
        <dd><%= o.warehouse.full_description %></dd>

        <dt><%= t 'activerecord.attributes.order.supplier' %>:</dt>
        <dd><%= o.supplier.corporate_name %></dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <span><%= t '.not_found_message' %></span>
<% end %>

app/views/orders/show.html.erb
<div style="display: flex; align-items: center; gap: 2rem;">
  <h2><%= t 'activerecord.models.order.one' %> <%= @order.code %></h2>

  <% if @order.pending? %>
    <%= button_to 'Marcar como Entregue', delivered_order_path(@order) %>
    <%= button_to 'Cancelar Pedido', canceled_order_path(@order) %>
  <% end %>
  
  <%= link_to 'Editar', edit_order_path(@order) %>
</div>

<%= render @order %>

<div style="display: flex; align-items: center; gap: 2rem;">
  <h2>Items do Pedido</h2>
  <%= link_to t('.add_item'), new_order_order_item_path(order_id: @order) %>
</div>

<div style="display: flex; flex-direction: column;">
  <% if @order.order_items.present? %>
    <% @order.order_items.each do |item| %>
      <span><%= item.quantity %> x <%= item.product_model.name %></span>
    <% end %>
  <% else %>
    <p><%= t '.items_not_found_message' %></p>
  <% end %>
</div>