config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  root 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create]
  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      post 'delivered'
      post 'canceled'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:index, :show, :create]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models
  
  validates :brand_name, :corporate_name, :registration_number, :full_address, :city, :state, :email, presence: true
  validates :registration_number, length: { is: 14 }
  validates :registration_number, uniqueness: true

  def description
    "#{brand_name} | #{corporate_name} | CNPJ: #{registration_number}"
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update]

  def index
    @suppliers = Supplier.all
  end

  def show
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to @supplier, notice: 'Fornecedor cadastrado com sucesso.'
    else
      flash.now[:notice] = 'Falha ao cadastrar o fornecedor.'
      render :new
    end
  end

  def edit
  end

  def update
    if @supplier.update(supplier_params)
      redirect_to @supplier, notice: 'Fornecedor atualizado com sucesso.'
    else
      flash.now[:notice] = 'Falha ao atualizar o fornecedor.'
      render :edit
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:brand_name, :corporate_name, :registration_number, :full_address, :city, :state, :email)
  end
end

app/views/suppliers/_form.html.erb
<%= form_with model: @supplier do |f| %>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  
  <%= f.submit 'Enviar' %>
<% end %>

app/views/suppliers/edit.html.erb
<h2><%= I18n.t 'views.suppliers.edit_supplier' %></h2>

<% if @supplier.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  
  <% @supplier.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h2><%= I18n.t 'activerecord.models.supplier.other' %></h2>

<%= link_to 'Cadastrar Fornecedor', new_supplier_path %>
<%= link_to 'Voltar', root_path %>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th><%= I18n.t 'views.suppliers.name' %></th>
        <th><%= I18n.t 'views.suppliers.localization' %></th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= link_to supplier.brand_name, supplier %></td>
          <td><%= supplier.city %> - <%= supplier.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>Não existem fornecedores cadastrados.</p>
<% end %>

app/views/suppliers/new.html.erb
<h3><%= I18n.t 'views.suppliers.new_supplier' %></h3>

<% if @supplier.errors.any? %>
  <p>Verifique os erros abaixo:</p>
  
  <% @supplier.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/suppliers/show.html.erb
<h2><%= @supplier.corporate_name %></h2>

<div>
  <dl>
    <dt><strong><%= I18n.t 'activerecord.attributes.supplier.registration_number' %>:</strong></dt>
    <dd><%= @supplier.registration_number %></dd>

    <dt><strong><%= I18n.t 'activerecord.attributes.supplier.full_address' %>:</strong></dt>
    <dd><%= @supplier.full_address %> - <%= @supplier.city %>, <%= @supplier.state %></dd>

    <dt><strong><%= I18n.t 'activerecord.attributes.supplier.email' %>:</strong></dt>
    <dd><%= @supplier.email %></dd>
  </dl>
</div>

<%= button_to 'Remover', @supplier, method: :delete %>
<%= link_to 'Editar', edit_supplier_path(@supplier) %>